apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-frontend-component-dev
  namespace: ontada-mcp-dev
  labels:
    backstage.io/kubernetes-id: mcp-frontend-component-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-frontend-component-dev
  template:
    metadata:
      labels:
        app: mcp-frontend-component-dev
        backstage.io/kubernetes-id: mcp-frontend-component-dev
        appContact: "ajay_maharashi"
        github: "mcp-frontend-component"
        appVersion: "${IMAGE_TAG}"
    spec:
      containers:
        - name: mcp-frontend-component-dev
          image: "${DOCKER_REGISTRY}/mcp-frontend-component:${IMAGE_TAG}"
          ports:
            - containerPort: 6006
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 200Mi
      imagePullSecrets:
        - name: docker-registry-credentials # TODO: Create this Kubernetes Secret with your jFrog credentials (example in SECRETS.md)

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-frontend-component-dev-svc
  namespace: ontada-mcp-dev
  labels:
    app: mcp-frontend-component-dev
    backstage.io/kubernetes-id: mcp-frontend-component-dev
spec:
  ports:
    - protocol: TCP
      port: 6006
  selector:
    app: mcp-frontend-component-dev
  type: ClusterIP
