export const DatePickerMockData = {
  id: "test-id",
  dateRange: ["", ""],
  size: "md",
  isCustomInput: false,
  dateFormat: "MM/DD/YYYY",
  isShowRequiredLabel: false,
  isRequired: false,
  isReadonly: false,
  isDisabled: false,
  isEndDateError: false,
  isStartDateError: false,
  endDateHelperMessage: "",
  startDateHelperMessage: "",
  isEndDateSuccess: false,
  isStartDateSuccess: false,
  endDateLabel: "End Date",
  startDateLabel: "Start Date",
  isDateRangeCleared: false,
  requiredLabel: "",
  clearLabel: "",
  confirmLabel: "",
  extraClassName: "",
  lang: "en",
};
