name: Release new version
on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Configure GitHub Package Registry
        run: npm config set @mckesson-ontada:registry https://npm.pkg.github.com

      - name: Set npm auth token for GitHub Package Registry
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          npm run publish-library
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes as version update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated to the latest version"
          git push
